import type { Metadata } from "next";

import { Container } from "@/components/layout/container";
import { brand } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `How ${brand.shortName} handles the information you share with us.`,
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <section className="py-20 md:py-28">
      <Container className="max-w-2xl">
        <span className="font-mono-eyebrow text-xs uppercase tracking-wider text-accent-deep">
          Legal
        </span>
        <h1 className="mt-4 font-heading text-4xl font-semibold tracking-tight text-ink">
          Privacy Policy
        </h1>
        <p className="mt-4 text-sm text-ink-soft">Last updated: 26 July 2026</p>

        <div className="prose-content mt-10 space-y-8 text-base leading-relaxed text-ink-soft">
          <p>
            {brand.legalName} ({brand.shortName}) respects your privacy.
            This page explains what information we collect through this
            website and our software, and what we do with it.
          </p>

          <div className="space-y-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              What we collect
            </h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>
                <strong className="text-ink">Contact &amp; enquiries</strong>
                {" — "}name, email, and message content when you use the
                contact form, WhatsApp, or email us directly.
              </li>
              <li>
                <strong className="text-ink">Accounts</strong>
                {" — "}your email address and a securely hashed password
                when you create a {brand.shortName} account. We never store
                your password in plain text.
              </li>
              <li>
                <strong className="text-ink">Product data</strong>
                {" — "}information you or your business enter into Pluto,
                Mars, or Venus, such as stock records, sales, invoices, or
                payroll data.
              </li>
              <li>
                <strong className="text-ink">Basic technical data</strong>
                {" — "}standard server logs (IP address, browser type,
                timestamps) generated by normal website operation.
              </li>
            </ul>
          </div>

          <div className="space-y-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              How we use it
            </h2>
            <p>
              We use this information to respond to enquiries, provide and
              maintain your account, deliver the software and services
              you&apos;ve requested, and send service-related emails (such as
              confirming your email address). We do not use your
              information for advertising, and this site does not run
              third-party analytics or ad-tracking scripts.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              Cookies
            </h2>
            <p>
              We use a single essential cookie to keep you signed in to your
              account or the {brand.shortName} dashboard. We don&apos;t use
              cookies for advertising or cross-site tracking.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              Who we share it with
            </h2>
            <p>
              We don&apos;t sell your personal information. We use a small
              number of service providers to run this site and our
              software — Vercel (hosting and file storage) and Resend
              (transactional email) — who process data on our behalf under
              their own security commitments. We don&apos;t share your
              information with anyone else except where required by law.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              Data retention
            </h2>
            <p>
              We keep account and product data for as long as your account
              is active, and contact-form enquiries for as long as needed to
              respond and keep a reasonable record. You can ask us to delete
              your account and associated data at any time from your
              account settings, or by emailing us.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="font-heading text-lg font-semibold text-ink">
              Your rights
            </h2>
            <p>
              You can ask us what personal information we hold about you,
              correct it, or ask us to delete it, by emailing the address
              below.
            </p>
          </div>

          <p>
            Questions about this policy can be sent to{" "}
            <a
              href={`mailto:${brand.email}`}
              className="text-accent-deep underline underline-offset-2"
            >
              {brand.email}
            </a>
            .
          </p>
        </div>
      </Container>
    </section>
  );
}
